services:
  service-postgres:
    image: postgres
    ports:
      - "5433:5432" # <host_port>:<container_port>
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: nlw-connect # The name of the database
  service-redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes # As docker compose is not used in production, only in development, we allow an empty password

  service-nlw-connect:
    build: .
    depends_on:
      - service-postgres
    ports:
      - "3333:3333"
    environment:
      PORT: 333
      WEB_URL: "http://localhost:3000"
      POSTGRES_URL: "postgresql://root:pwd@service-postgres/nlw-connect"
      REDIS_URL: "redis://service-redis"
