name: Deploy NLW Coonnect App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
    working-directory: ./server
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: server/package-lock.json # when we have multiple lock files (from server and web folder) or in a directory diferent than root, it should be specified the right directory
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      - name: Build website
        run: npm run build --if-present # only run code if script "build" exists in package.json
    # - run: npm test TODO- tests
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}

      - name: Extract Docker image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ritalanca/images-repository # <my-docker-hub-namespace>/<my-docker-hub-repository>

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:server" # Defines the build's context as the set of files located in the specified path.
          file: dockerfile
          # push: ${{ github.event_name != 'pull_request' }} # only pushes images for commits to the main branch
          push: true
          tags: ${{ steps.meta.outputs.tags }} # This is populated by output from metadata-action.
          labels: ${{ steps.meta.outputs.labels }} # This is populated by output from metadata-action.
          # tags: ritalanca/my-docker-hub/nlw-connect-api:latest
          # annotations: ${{ steps.meta.outputs.annotations }}
  deploy:
     uses: ./.github/workflows/deploy-app-job.yaml


