name: "📦 Vercel App Deployment"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_call:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # - name: generate endpoints with orval
      #   run: npx orval

      - name: Ensure correct working directory
        run: cd $GITHUB_WORKSPACE && ls -la

      - name: install Vercel CLI
        run: npm install --global vercel@latest

      - name: Debug Working Directory
        run: pwd && ls -la
      - name: Debug Web Directory
        run: ls -la ./web

      - name: pull Vercel Environment Information
        run: vercel pull --cwd web --yes --environment=production --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: ./web

    

      - name: build Project Artifacts
        run: vercel build --cwd web --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        # working-directory: ./web
      - name: deploy Project Artifacts to Vercel
        run: vercel deploy --cwd web --prebuilt --prod  --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        # working-directory: ./web

      
