name: "📦 Template - Deploy API"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
    
      # NOTE: At moment it's not being used docker image from registry. It's not needed this step
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}

      # NOTE: deploy to render via hook url
      - name: deploy to render    
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "$deploy_url"

      

