name: "📦 Template - Deploy APP"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
    
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
#          password: ${{ secrets.DOCKER_REGISTRY_PWD }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          dns-name-label: nlw-connect
          image: ritalanca/images-repository:main
          registry-login-server: docker.io
          registry-username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.DOCKER_REGISTRY_PWD }}
          name: nlw-connect
          location: 'west europe'


      

